### ISSUE TITLE
Compilation fails on Mac OSX due to 'clock_gettime'

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-binutils-gdb#35]
Not sure this is the same/related to #32. I also cannot compile on MAC OSX because of clock_gettime doesn't seem to be implemented on MAC:

```
 /Users/megan/freedom-e-sdk/riscv-gnu-toolchain/riscv-binutils-gdb/sim/riscv/sim-main.c:96:6: warning: 
      implicit declaration of function 'clock_gettime' is invalid in C99
      [-Wimplicit-function-declaration]
        if (clock_gettime (CLOCK_MONOTONIC, &ts) == 0)
            ^
/Users/megan/freedom-e-sdk/riscv-gnu-toolchain/riscv-binutils-gdb/sim/riscv/sim-main.c:96:21: error: 
      use of undeclared identifier 'CLOCK_MONOTONIC'
        if (clock_gettime (CLOCK_MONOTONIC, &ts) == 0)
```

**Comment by palmer-dabbelt** [comment]
The latest version (on riscv-next) of the RISC-V port shouldn't have clock_gettime() in sim.  This is part of the upstream cleanup process, which has gotten a bit bogged down because we have to deal with some ABI issues.

You can just build with "--disable-sim", since you're probably not using the GNU sim.

**Comment by palmer-dabbelt** [comment]
I'm closing this, I believe it's fixed.
