### ISSUE TITLE
objdump disassembly gives wrong instruction mnemonic csrrc instead of csrrci

### ISSUE THREAD

**Issue by makigumo** [riscv/riscv-binutils-gdb#36]
Hello, I think there is a small error in the disassembly.

The following instruction `1000f9f3` (in big endian) is disassembled to `csrrc   s3,sstatus,1` but should actually be `csrrci   s3,sstatus,1` as seems obvious by the immediate operand `1`. This is further backed upd by the spec 2.1 where `csrrci` is given for the `funct3` of `0b111`.

I'm using the bottled package (e.g. prebuilt) from https://github.com/riscv/homebrew-riscv

Thanks.

**Comment by aswaterman** [comment]
Hi.  csrrc can be used as a pseudo-instruction for csrrci.  However, the
disassembler should display it like you proposed.  I will fix it.

In general, the disassembler might choose a more idiomatic form, unless you
pass the flag -Mno-aliases.  For example, it displays "ret" instead of
"jalr zero, 0(ra)" by default.

**Comment by makigumo** [comment]
Thank you for your clarification. I'was only aware of the pseudo-instructions mentioned in the spec. Is there a different document containing those extra pseudo-instructions?

**Comment by aswaterman** [comment]
The assembly programmer's manual is incomplete, but as I mentioned, if you notice a pseudo-instruction you don't recognize, you can disassemble with -Mno-aliases to identify it.
